<div class="AtomicReach">
    <ul class="ARPostListH">
        
    <?php
    
        foreach ($view['posts'] AS $post) {
            ?>
            <li>   
                
                <h2><a href="<?php echo $post->url; ?>"><?php echo $post->title; ?></a></h2>
<?php
                if ($post->image){
                ?>
                
                <a href="<?php echo $post->url; ?>" class="feature">
                    <img src="http://images.weserv.nl/?h=100&w=100&t=square&url=<?php echo substr($post->image->original, 7); ?>"  width="100" height="100" alt="<?php echo $post->title; ?>" />
                </a>
                
                <div style="margin-left:110px;">
            <?php
            }   else {
                echo '<div>';
            }
            ?>

     
            <p><?php echo $post->teaser; ?></p>
            </div> 
<div style="clear:left;"></div>
            </li>
            
     <?php
            }      
            ?>
            
</ul>
    <?php

        if ($view['options']['loadmore']  == 'true'){
            echo '   <a href="' . $view['loadmoreUrl']  . '" class="loadmore">Load More</a>';
        }
    ?>
     
</div>