<div class="AtomicReach">
    <ul class="ARUserH">
        
    <?php

        foreach ($users AS $user) {
    
    ?>
<li>   
<a href="http://www.atomicreach.com/user/<?php echo $user->url; ?>" class="feature" ><img src="<?php echo $user->user->image->{128}; ?>"width="100" height="100" alt="<?php echo $user->user->username; ?>" /></a>

    <div class="block">
           <h2><a href="http://www.atomicreach.com/user/<?php echo $user->url; ?>"><?php echo $user->user->username; ?></a></h2>
        <p><?php 
           echo trim(substr($user->user->bio, 0,  200)); 
          if (strlen($user->user->bio) >= 200) echo '...';
        ?></p>
    </div>
<div style="clear: left;"></div> 
       </li>
            
     <?php
            }      
      ?>
        
</ul>
</div>