<div class="AtomicReach">
<ul class="ARUserGrid">
        
    <?php
    
        foreach ($users AS $user) {

            ?>
            <li>   
                <a href="http://www.atomicreach.com/user/<?php echo $user->user->username; ?>"><img src="<?php echo $user->user->image->{64}; ?>" alt="<?php echo $user->user->username; ?>" width="55" height="55" /></a>
            </li>
            
     <?php
            }      
            ?>
        
</ul>
</div>
        